FROM node:latest
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm install express
RUN npm install mysql
RUN npm install cors
RUN npm install dotenv
RUN npm install -g nodemon
RUN npm install k6
CMD ["nodemon", "server.js"]
EXPOSE 3000
