/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppConfirmation: typeof import('./components/AppConfirmation.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppQrReader: typeof import('./components/AppQrReader.vue')['default']
    AppTipoUsuario: typeof import('./components/AppTipoUsuario.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplashScreen: typeof import('./components/SplashScreen.vue')['default']
  }
}
